export type Property = {
  id: string;
  title: string;
  description: string;
  property_type: string;
  listing_type: string;
  price: number;
  area_sqft: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  parking: number | null;
  furnished: string | null;
  year_built: number | null;
  city: string;
  state: string | null;
  country: string | null;
  locality: string | null;
  pin_code: string | null;
  lat: number | null;
  lng: number | null;
  images: string[];
  amenities: string[];
  agent_name: string | null;
  agent_phone: string | null;
  agent_email: string | null;
  is_featured: boolean;
  views: number;
  created_at: string;
};
